DROP TABLE IF EXISTS `bookings`; 
CREATE TABLE `bookings` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
`user_id` int(11) NOT NULL,`CLIENT_FIRST_NAME` varchar(512) NOT NULL,`CLIENT_LAST_NAME` varchar(512) NOT NULL,`STAFF_FIRST_NAME` varchar(512) NOT NULL,`STAFF_LAST_NAME` varchar(512) NOT NULL,`BOOKING_DATE_TIME` varchar(512) NOT NULL,`BOOKING_DATE` varchar(512) NOT NULL,`BOOKING_TIME` varchar(512) NOT NULL,`BOOKING_REFERENCE` varchar(512) NOT NULL,`SERVICE_NAME` varchar(512) NOT NULL,`BUSINESS_NAME` varchar(512) NOT NULL,`LOCATION_NAME` varchar(512) NOT NULL,`LOCATION_PHONE` varchar(512) NOT NULL,`BOOKING_END_DATE_TIME` varchar(512) NOT NULL,`color` varchar(512) NOT NULL,
PRIMARY KEY(`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;